version: "2"
services:
  kdc:
    image: "jakelow/kdc:latest"
    hostname: kdc.localdomain
    volumes:
      - ./etc/krb5.conf:/etc/krb5.conf
      - ./etc/kdc.conf:/etc/kdc.conf
      - /dev/urandom:/dev/random
      - kdb:/var/lib/krb5kdc
    expose:
      - 88
    user: root
    command: krb5kdc -n

  namenode:
    image: "jakelow/hadoop:2"
    hostname: namenode.localdomain
    links:
      - kdc
    volumes:
      - ./etc/hadoop:/etc/hadoop
      - ./etc/krb5.conf:/etc/krb5.conf
      - keytab:/etc/security/keytab
      - nn_ssl:/etc/security/ssl
    expose:
      - 8020
      - 50070
    user: hdfs
    command: hdfs namenode

  datanode:
    image: "jakelow/hadoop:2"
    links:
      - kdc
      - namenode
    volumes:
      - ./etc/hadoop:/etc/hadoop
      - ./etc/krb5.conf:/etc/krb5.conf
      - keytab:/etc/security/keytab
      - dn_ssl:/etc/security/ssl
    expose:
      - 50010
      - 50020
      - 50075
    user: hdfs
    command: hdfs datanode

  resourcemanager:
    image: "jakelow/hadoop:2"
    hostname: resourcemanager.localdomain
    links:
      - kdc
      - namenode
    volumes:
      - ./etc/hadoop:/etc/hadoop
      - ./etc/krb5.conf:/etc/krb5.conf
      - keytab:/etc/security/keytab
      - rm_ssl:/etc/security/ssl
    expose:
      - 8032
      - 8088
    user: yarn
    command: yarn resourcemanager

  nodemanager:
    image: "jakelow/hadoop:2"
    links:
      - kdc
      - resourcemanager
      - namenode
    volumes:
      - ./etc/hadoop:/etc/hadoop
      - ./etc/krb5.conf:/etc/krb5.conf
      - keytab:/etc/security/keytab
      - nm_ssl:/etc/security/ssl
    expose:
      - 50060
    user: yarn
    command: yarn nodemanager

volumes:
  kdb:
    driver: local
  keytab:
    driver: local
  nn_ssl:
    driver: local
  dn_ssl:
    driver: local
  rm_ssl:
    driver: local
  nm_ssl:
    driver: local
