namenode:
  image: "hadoop:2.7.0"
  hostname: namenode.localdomain
  dns: 172.17.42.1
  dns_search: localdomain
  volumes:
    - ./etc/hadoop:/etc/hadoop
  expose:
    - 8020
    - 50070
  user: hdfs
  command: hdfs namenode

datanode:
  image: "hadoop:2.7.0"
  dns: 172.17.42.1
  dns_search: localdomain
  volumes:
    - ./etc/hadoop:/etc/hadoop
  expose:
    - 50010
    - 50020
    - 50075
  user: hdfs
  command: hdfs datanode

resourcemanager:
  image: "hadoop:2.7.0"
  hostname: resourcemanager.localdomain
  dns: 172.17.42.1
  dns_search: localdomain
  volumes:
    - ./etc/hadoop:/etc/hadoop
  expose:
    - 8032
    - 8088
  user: yarn
  command: yarn resourcemanager

nodemanager:
  image: "hadoop:2.7.0"
  dns: 172.17.42.1
  dns_search: localdomain
  volumes:
    - ./etc/hadoop:/etc/hadoop
  expose:
    - 50060
  user: yarn
  command: yarn nodemanager
