version: "2"
services:
  namenode:
    image: "jakelow/hadoop:2"
    hostname: namenode
    volumes:
      - ./etc/hadoop:/etc/hadoop
    user: hdfs
    command: hdfs namenode

  datanode:
    image: "jakelow/hadoop:2"
    links:
      - namenode
    volumes:
      - ./etc/hadoop:/etc/hadoop
    user: hdfs
    command: hdfs datanode

  resourcemanager:
    image: "jakelow/hadoop:2"
    hostname: resourcemanager
    links:
      - namenode
    volumes:
      - ./etc/hadoop:/etc/hadoop
    user: yarn
    command: yarn resourcemanager

  nodemanager:
    image: "jakelow/hadoop:2"
    links:
      - resourcemanager
      - namenode
    volumes:
      - ./etc/hadoop:/etc/hadoop
    user: yarn
    command: yarn nodemanager
